Audit log fixes
US-CBP/GTAS pull request #1969
Opened 2020-11-23 21:11 UTC by tjwdev

Sister backend PR for AuditLogFixes branch on GTAS-UI
Fixes #428 on GTAS-UI side
-Pulled actions from enumerated list
-Fixed dates not working
-Fixed ALL_ACTIONS showing up and working correctly
-Removed base "Select Action" from drop down
-Merged Kasim's changes for re-adding OrderBy for search

2020-11-24 19:03 UTC, tjwdev commented
This now also resolves #429 on GTAS-UI side.

2020-11-24 20:55 UTC, gtasautumn commented on gtas-parent/gtas-webapp/src/main/java/gov/gtas/controller/AdminController.java
> +	      params.remove("actionType"); //Correctly allows for search criteria to be built for ALL_ACTIONS.
So this works, BUT if we are just removing it here wouldn't it be easier just not to send the code from the frontend? I noticed it because including it as an enum causes the `ALL_ACTIONS` option to be ordered beneath `ACCESS_INFORMATION` . If the backend really doesn't need the ALL tag, its simpler for the front-end to append a dummy option at the top of the dropdown list to represent the ALL option and just not send it when the default is selected.

2020-11-24 21:09 UTC, gtasautumn requested changes
Everything works, but the sort here prevents ALL_ACTIONS from displaying at the top of the dropdown on the frontend.

2020-11-24 21:20 UTC, kasimhelil commented on gtas-parent/gtas-webapp/src/main/java/gov/gtas/controller/AdminController.java
> +	      params.remove("actionType"); //Correctly allows for search criteria to be built for ALL_ACTIONS.
Making action's input not required on the front end should be enough, I think. 
And then we can remove ALL_ACTIONS enum from both the frontend and backend. 
Not selecting any action types means give me all; right?

2020-11-24 21:27 UTC, tjwdev commented on gtas-parent/gtas-webapp/src/main/java/gov/gtas/controller/AdminController.java
> +    actionList.sort(Comparator.comparing(AuditActionType::name));
The solution will be applied as such: 
1. Front-end will generate the "ALL_ACTIONS"/"ALL_CODES" and put at the top of the list. (Force "ALL" to always be top option)

2. Front-end will not send the parameter for action/code if those are the values. (Remove clunky-parameter removal)

2020-11-24 21:32 UTC, tjwdev commented on gtas-parent/gtas-webapp/src/main/java/gov/gtas/controller/AdminController.java
> +	      params.remove("actionType"); //Correctly allows for search criteria to be built for ALL_ACTIONS.
I think all actions (and codes) is a valuable thing for the user to see/use, so I'm not so certain on the front-end it needs to be removed. But having it never get sent back as an actual parameter will work in order to remove it from the backend enum, which ,agreed, it does not need to be in.

2020-11-24 21:32 UTC, kasimhelil commented on gtas-parent/gtas-webapp/src/main/java/gov/gtas/controller/AdminController.java
> +    actionList.sort(Comparator.comparing(AuditActionType::name));
I am for removing the `ALL_ACTIONS`/`ALL_CODES` options and setting required to false. 
And just have a place holder, something like `Select actions` /`Select codes`

2020-11-27 21:14 UTC, gtasautumn approved these changes

2020-11-27 21:14 UTC, merged